### ISSUE TITLE
how to import generated code to TLSharp

### ISSUE THREAD

**Issue by amirsafiallah** [LonamiWebs/TLSharp.CodeGenerator#1]
Hello dear @XyLoNaMiyX ,
Please explain about how to use the generated scheme.cs in [TLSharp](https://github.com/sochix/TLSharp):

1. where TBinaryReader, TBinaryWriter should be put in TLSharp.

2. are implementation of  telegram functions in the same way as TLSharp? 

Thanks,

**Comment by XyLoNaMiyX** [comment]
I can't do your job. This is only a code generator. You're the one who needs to look at the code and understand it. I'm not working on this any more, so I cannot help you anyway.
