### ISSUE TITLE
how Add to tlsharp

### ISSUE THREAD

**Issue by mohsen2014** [LonamiWebs/TLSharp.CodeGenerator#2]
Hi
I tried  add scheme.cs to the project Tlsharp, but 
binaryRead , binarywrite ,TelegramClient,Request....Were error
More than 80 errors occurred
how to fix it?
You can send for me tlsharp dll?
tnx

**Comment by XyLoNaMiyX** [comment]
Sorry, I no longer work on this project. You can inspect the code of the generator at your desire.

**Comment by mohsen2014** [comment]
please tell me how to fix this errors

**Comment by XyLoNaMiyX** [comment]
They are over 80 errors. I no longer work in the project. There's no way I can tell you how to fix the errors, sorry. Furthermore, this is probably outdated and won't work with the latest version of TLSharp.
